version: "3"

services:

  fdk-sparql-service:
    image: eu.gcr.io/digdir-fdk-infra/fdk-sparql-service:latest
    ports:
      - "3030:8080"

  rabbitmq:
    image: rabbitmq:3.8.2-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
