logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
  level.org.apache.jena: ERROR
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
server:
  port: 8080
application:
  uri:
    datasets: http://fdk-dataset-harvester:8080/catalogs
    dataservices: http://fdk-dataservice-harvester:8080/catalogs
    concepts: http://fdk-concept-harvester:8080/concepts
    informationmodels: http://fdk-informationmodel-harvester:8080/catalogs
    events: http://fdk-event-harvester:8080/events
    organizations: http://organization-catalogue:8080/organizations
    publicservices: http://fdk-public-service-harvester:8080/public-services
    sparqlservice: http://fdk-sparql-service:8080

---
spring:
  config.activate.on-profile: develop
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
application:
  uri:
    datasets: https://datasets.staging.fellesdatakatalog.digdir.no/catalogs
    dataservices: https://dataservices.staging.fellesdatakatalog.digdir.no/catalogs
    concepts: https://concepts.staging.fellesdatakatalog.digdir.no/concepts
    informationmodels: https://informationmodels.staging.fellesdatakatalog.digdir.no/catalogs
    events: https://staging.fellesdatakatalog.digdir.no/api/events
    organizations: https://organization-catalogue.staging.fellesdatakatalog.digdir.no/organizations
    publicservices: https://staging.fellesdatakatalog.digdir.no/api/public-services
    sparqlservice: http://localhost:3030

---
spring:
  config.activate.on-profile: test
application:
  uri:
    datasets: http://localhost:5000/datasets/catalogs
    dataservices: http://localhost:5000/dataservices/catalogs
    concepts: http://localhost:5000/concepts
    informationmodels: http://localhost:5000/informationmodels/catalogs
    events: http://localhost:5000/events
    organizations: http://localhost:5000/organizations
    publicservices: http://localhost:5000/public-services
    sparqlservice: http://localhost:5000
