name: Deploy as Google function

on:
  push:
    branches:
      - master

jobs:
  build-test-and-deploy-production:
    name: Deploy on merge to master branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.DIGDIR_CLOUD_FUNCTIONS_SA_EMAIL }}
          service_account_key: ${{ secrets.DIGDIR_CLOUD_FUNCTIONS_SA_KEY }}

      - name: Deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: fdk-data-transformation-service
          runtime: java11
          entry_point: no.fdk.fdk_data_transformation_service.DataTransformationService
          memory: 1024
          region: europe-west1
          max_instances: 1

      - name: Notify slack
        uses: 8398a7/action-slack@v3
        with:
          mention: 'channel'
          if_mention: failure
          status: ${{ job.status }}
          author_name: 'Application: fdk-data-transformation-service'
          fields: commit,author,workflow,message
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
